-- MySQL Script generated by MySQL Workbench
-- Wed Jul 19 10:48:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tabeladb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tabeladb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tabeladb` DEFAULT CHARACTER SET utf8 ;
USE `tabeladb` ;

-- -----------------------------------------------------
-- Table `tabeladb`.`experimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tabeladb`.`experimentos` (
  `idexperimentos` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` LONGTEXT NULL,
  `videolink` LONGTEXT NULL,
  PRIMARY KEY (`idexperimentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tabeladb`.`elementos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tabeladb`.`elementos` (
  `nome` VARCHAR(45) NOT NULL,
  `abbreviation` VARCHAR(45) NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `numatom` INT NULL,
  PRIMARY KEY (`abbreviation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tabeladb`.`experimentos_has_elementos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tabeladb`.`experimentos_has_elementos` (
  `experimentos_idexperimentos` INT NOT NULL,
  `elementos_abbreviation` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`experimentos_idexperimentos`, `elementos_abbreviation`),
  INDEX `fk_experimentos_has_elementos_elementos1_idx` (`elementos_abbreviation` ASC) VISIBLE,
  INDEX `fk_experimentos_has_elementos_experimentos_idx` (`experimentos_idexperimentos` ASC) VISIBLE,
  CONSTRAINT `fk_experimentos_has_elementos_experimentos`
    FOREIGN KEY (`experimentos_idexperimentos`)
    REFERENCES `tabeladb`.`experimentos` (`idexperimentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_experimentos_has_elementos_elementos1`
    FOREIGN KEY (`elementos_abbreviation`)
    REFERENCES `tabeladb`.`elementos` (`abbreviation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
